
name: Documentation Issue
description: "Create a report to help fixing documentation"
title: 'DOCUMENT'
labels: ['documentation']
body:
- type: markdown
  attributes:
    value: |
      Report any improvement or fix for the documentation

- type: textarea
  attributes:
    label: Location
    description: Please provide the location in the documentation where the issue exists. This could be a URL or a page reference.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Issue
    description: A clear and concise description of the issue.
  validations:
    required: true
  

- type: textarea
  attributes:
    label: Suggested Revision
    description: If possible, suggest a way to revise or address the documentation issue.

- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context about the problem or helpful external resources.
